In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3=np.zeros((2,3))

In [9]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4=np.ones((3,3))

In [11]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5=np.identity(5)

In [13]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6=np.arange(10)

In [15]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7=np.arange(5,50,5)

In [17]:
arr7

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
arr8=np.linspace(10,20,10)

In [19]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
arr9=arr8.copy()

In [21]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**Properties & Attributes**


1.   Shape
2.   nDim

1.   Size

1.   Itemsize
2.   Dtype

1.   astype()








In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
arr1.shape

(5,)

In [24]:
arr1.ndim

1

In [25]:
arr1.size

5

In [26]:
arr1.itemsize

8

In [27]:
arr1.dtype

dtype('int64')

In [28]:
arr1.dtype

dtype('int64')

In [29]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [30]:
arr1.dtype

dtype('int64')

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2.shape

(2, 3)

In [33]:
arr2.ndim

2

In [34]:
arr2.size

6

In [35]:
arr2.itemsize

8

In [36]:
arr2.dtype

dtype('int64')

In [37]:
arr2.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr2.dtype

dtype('int64')

**Python list Vs Numpy arrays**


1.   Faster
2.   Convenient

1.   Less Memory






In [52]:
lista=range(100)
lista
arr11=np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
import sys

In [41]:
print(sys.getsizeof(87)*len(lista))

2800


In [42]:
print(arr11.itemsize*arr11.size)

800


In [43]:
import time

In [44]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
c=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

2.364354133605957


In [45]:
x=np.arange(10000000)
y=np.arange(10000000,20000000)
start_time=time.time()
c=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time) 

2.842071533203125


In [46]:
arr10=np.arange(24).reshape(6,4)

In [47]:
arr10[2]

array([ 8,  9, 10, 11])

In [48]:
arr10[2][3]

11